name: CI/CD Pipeline

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: mydatabase
          POSTGRES_USER: myuser
          POSTGRES_PASSWORD: mypassword
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U myuser"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13.0'  #Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations
        working-directory: C:\Users\nysop\Desktop\Django\finance_backtester\manage.py  # Update this to your actual folder 
        env:
          DATABASE_URL: postgres://myuser:mypassword@localhost/mydatabase
        run: |
          python manage.py migrate

      - name: Run tests
        working-directory: C:\Users\nysop\Desktop\Django\finance_backtester\manage.py  # Update this to your actual folder structure
        run: |
          python manage.py test

      - name: Build Docker image
        run: |
          docker build -t mydjangoapp .

      - name: Deploy to your cloud provider (e.g., AWS)
        run: |
          echo "Deploying application..."